<center>
    <img src="logo.png" width="175" alt="Descripción de la imagen">
</center>

<span style="display: block; text-align: center; font-family: Time New Roman; font-size: 24px; color: black; text-decoration: underline">**Identify all companies in a country in Refinitiv via python**</span>

<span style="display: block; text-align: right; font-family: Time New Roman; font-size: 10px; color: black; text-decoration: underline">**Author: Luisa M Rodríguez-Fajardo** </span>

<span style="display: block; text-align: left; font-family: Time New Roman; font-size: 18px; color: black; text-decoration: underline">**Step 1. Import all libraries to be necessary**</span>

In [1]:
# Import Libraries

#Refinitiv Eikon Libraries 
import eikon as ek 
ek.set_app_key('Eikon Key') 
from datetime import datetime
import refinitiv.data as rd

# Others Libraries
import numpy as np
import pandas as pd
import cufflinks as cf
import matplotlib as plt
import yfinance as yf
import seaborn as sns

In [2]:
# Ignore unnecessary warnings. 
import warnings
warnings.filterwarnings('ignore')

<span style="display: block; text-align: left; font-family: Time New Roman; font-size: 14px; color: black"> Remember that when using Python for downloader data from Refinitiv, you will need either each stock´s PermID or Ticket symbol. (Explined in the script "Variable Code Finder in Refinitiv"). In this case you will need the code of country. (Example: Mexico=MX, United State = US, etc.)</span>

<span style="display: block; text-align: left; font-family: Time New Roman; font-size: 18px; color: black;text-decoration: underline">**Step 2. Download Refinitiv data.**</span>

<span style="display: block; text-align: left; font-family: Time New Roman; font-size: 14px; color: black">This code returns the same information as if you use the Refinitiv screener. The main advantage of using python to know information about all the companies that operate in a country is mainly that you can obtain the complete list, whereas Refinitiv is limited to showing only 5,000 and you can export 10,000 to excel. With python you have access to the full list.</span>

In [3]:
# Extract all companies of one country from Refinitiv (Example: Mexico)

# You can specify between public companies, private companies, whether they are active or inactive. 
#Also, add the rest of the information you want to obtain.


df, err = ek.get_data('SCREEN(U(IN(Equity(active or inactive, private,primary))), IN(TR.HQCountryCode,"MX"))',
                      ['TR.CommonName','TR.OrganizationID','TR.HeadquartersCountry','TR.UltimateParent',
                       'TR.TRBCEconomicSector','TR.TRBCIndustry','TR.NAICSSector',
                       'TR.NAICSSubsector','TR.NAICSIndustryGroup','TR.NACEClassification'])

df

,Instrument,Company Common Name,Organization PermID,Country of Headquarters,Organization Ultimate Parent,TRBC Economic Sector Name,TRBC Industry Name,NAICS Sector Name,NAICS Subsector Name,NAICS Industry Group Name,NACE Classification
0,4295966676,Siefore Banamex Basica 2 SA de CV,4295966676,Mexico,Siefore Banamex Basica 2 SA de CV,Financials,Pension Funds,Finance and Insurance,"Funds, Trusts, and Other Financial Vehicles",Insurance and Employee Benefit Funds,Pension funding (NACE) (65.30)
1,4296031399,Finde 1 SA de CV Sociedad de Inversion en Inst...,4296031399,Mexico,Finde 1 SA de CV Sociedad de Inversion en Inst...,Financials,Corporate Financial Services,Finance and Insurance,"Funds, Trusts, and Other Financial Vehicles",Other Investment Pools and Funds,"Trusts, funds and similar financial entities (..."
2,4296113089,Fondo de Inversiones Banamex SA de CV Fondo de...,4296113089,Mexico,Citigroup Inc,Financials,Corporate Financial Services,Finance and Insurance,Credit Intermediation and Related Activities,Nondepository Credit Intermediation,"Other financial service activities, except ins..."
3,4297258155,Asigna Compensacion y Liquidacion fideicomiso ...,4297258155,Mexico,Asigna Compensacion y Liquidacion fideicomiso ...,Industrials,Business Support Services,Finance and Insurance,Credit Intermediation and Related Activities,Activities Related to Credit Intermediation,Other activities auxiliary to financial servic...
4,4297968576,"Fondo Liquido Finamex, S.A. de C.V., Fondo de ...",4297968576,Mexico,"Fondo Liquido Finamex, S.A. de C.V., Fondo de ...",,,,,,
...,...,...,...,...,...,...,...,...,...,...,...
83944,5087060173,Kletos & Sanna SC,5087060173,Mexico,,,,,,,
83945,5087060317,Fideicomiso No F/000239 Con GBM Grupo Bursatil...,5087060317,Mexico,,,,,,,
83946,5087074256,Beliveo SA de CV,5087074256,Mexico,,Industrials,Business Support Services,Administrative and Support and Waste Managemen...,Administrative and Support Services,Business Support Services,
83947,5087074372,Legalario SA de CV,5087074372,Mexico,,Technology,Software,Information,Publishing Industries,Software Publishers,
83948,5087074378,Reboot Technologies SAPI de CV,5087074378,Mexico,,Technology,Software,Information,Publishing Industries,Software Publishers,

<span style="display: block; text-align: left; font-family: Time New Roman; font-size: 14px; color: black">If you want to add filters to the search.</span>

In [4]:
# Define SCREENER syntax 

# Example:Companies in US that Market Cap is greater than 2,000M USD, in NYSE, in Energy business 
# and 6 months return is more than 5%"

syntax = 'SCREEN(U(IN(Equity(active,public,primary))),IN(TR.HQCountryCode,"US"), TR.CompanyMarketCap>=5000000000, \
IN(TR.ExchangeMarketIdCode,"XNYS"), IN(TR.TRBCBusinessSectorCode,"5010","5020","5030"), \
TR.TotalReturn6Mo>=5, CURN=USD)'

fields = ["TR.CommonName","TR.CompanyMarketCap","TR.ExchangeName","TR.TRBCBusinessSector","TR.TotalReturn3Mo"]

#Get data

df,e = ek.get_data(syntax, fields)

df

,Instrument,Company Common Name,Company Market Cap,Exchange Name,TRBC Business Sector Name,3 Month Total Return
0,DINO.N,HF Sinclair Corp,10799732516.940001,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,11.97839
1,OKE.N,ONEOK Inc,41937827340.660004,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,9.58016
2,EPD.N,Enterprise Products Partners LP,59183702831.75,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,5.706858
3,VLO.N,Valero Energy Corp,47506803526.68,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,13.29863
4,ET.N,Energy Transfer LP,49000872439.800003,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,10.044956
5,CQP.N,Cheniere Energy Partners LP,25174874787.23,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,-10.521396
6,TRGP.N,Targa Resources Corp,21632680889.220001,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,13.342095
7,MPC.N,Marathon Petroleum Corp,62563680000.0,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,14.94929
8,PSX.N,Phillips 66,63270011240.75,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,24.482255
9,SUN.N,Sunoco LP,5279289655.77,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,15.39715
10,MPLX.N,MPLX LP,39077501227.32,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,11.094724
11,WES.N,Western Midstream Partners LP,11062902156.35,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,4.18152
12,MUSA.N,Murphy USA Inc,8280204087.04,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,9.924592
13,HESM.N,Hess Midstream LP,7531566448.64,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,8.324182
14,PR.N,Permian Resources Corp,11261770465.65,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,9.728507
15,AM.N,Antero Midstream Corp,5953548580.0,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,-2.823309
16,DTM.N,DT Midstream Inc,5304781713.2,"NEW YORK STOCK EXCHANGE, INC.",Energy - Fossil Fuels,-1.472743

<span style="display: block; text-align: left; font-family: Time New Roman; font-size: 14px; color: black">End
</span>